### ISSUE TITLE
"Wait for network to be configured"로 인한 서버 부팅 지연 문제

### ISSUE THREAD

**Issue by lkaybob** [kaist-cp/infra-public#48]
## 현상

오늘 오후부터 `ssh -J sunghyuk.kay@cp-expr.kaist.ac.kr ubuntu@10.30.251.9`(Alveo machine) 을 재부팅 후 접속 시도를 하면 아래와 같은 로그를 내뱉으며 부팅이 비정상적으로 늦어지는 점을 확인했습니다.

## 원인

IPMI KVM에서 부팅 로그 확인해보니 Ubuntu 부팅 중 실행되는 cloud-init 과정 중 "Wait for network to be configured" 단계부터 막히는 것을 확인했습니다. (#34 의 문제와 유사해보입니다.)
* 랜선 연결은 잘 되어서 NIC의 LED indicator로 Link up이 확인이 됨에도 부팅이 block 됨

## 해결책

netplan configuration에 `optional: true`를 추가하면 각 interface들에 대한 network configuration 테스트를 생략해 부팅이 block되는 것을 막을 수 있다고 합니다. ([링크](https://netplan.io/examples/#configuring-interface-bonding))

```
Note the ‘optional: true’ key declarations that allow booting to occur without waiting for those interfaces to activate fully.
```

일단 workaround로 netplan yaml 파일을 만들고 적용해봐서 문제가 해결됨을 확인했는데, 아예 MAAS쪽에서 해당 설정을 하는 것은 어떨까 합니다.

## 참고

`/etc/netplan/50-cloud-init.yaml`
```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
(생략)
```

`/etc/netplan/51-optional.yaml` (직접 만들어서 적용한 설정 파일)
```yaml
network:
    ethernets:
        enp193s0:
            optional: true
        enp194s0:
            optional: true
        enp65s0f0:
            optional: true
        enp65s0f1:
            optional: true
    version: 2
```
